[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://adhnfcickkvtyzvytacq.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkaG5mY2lja2t2dHl6dnl0YWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjU1ODcsImV4cCI6MjA2NTM0MTU4N30.sW2w7IldG-pXfKfKdHwIF2rTGf7reaJQ7BDuMl3xCTQ"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_api/:splat"
  status = 200
